server:
  port: 18080
  shutdown: graceful
#  ssl:
#    enabled: false
#    key-store: classpath:container-sit.testesunbank.com.tw.jks
#    key-store-password: ENC(KXcrgSoHASfYwGk2mmH8sRwkr4+DHY/kez+vPE0Pz2pRoYGWMjqw+r1eVs/41i6m)
#    key-store-type: JKS
spring:
  application:
    name: bigstock-biz
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: ${SPRING_CONSUL_HOST}
      port: ${SPRING_CONSUL_PORT}       
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  sleuth:
    sampler:
      probability: 1.0      
  redis:
    host: ${SPRING_REDIS_HOST}
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: ${SPRING_REDIS_PORT}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    pool:
      channelCacheSize: 5        
logging:
  config: classpath:logback.xml

  
springdoc:
  api-docs:
    path: /biz/swagger/v3/api-docs  
  swagger-ui:
    path: /biz/swagger/swagger-ui.html  
    
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: ${OPENTRACING_JAEGER_HTTP-SENDER}
      #http://localhost:14268/api/traces
    sampler:
      type: const
      param: ${OPENTRACING_JAEGER_SAMPLER_PARAM}
    reporter:
      log-spans: true
      flush-interval: 1000
      max-queue-size: 10000   
