server:
  port: 18080
  shutdown: graceful
#  ssl:
#    enabled: false
#    key-store: classpath:container-sit.testesunbank.com.tw.jks
#    key-store-password: ENC(KXcrgSoHASfYwGk2mmH8sRwkr4+DHY/kez+vPE0Pz2pRoYGWMjqw+r1eVs/41i6m)
#    key-store-type: JKS
spring: 
  application:
    name: bigstock-biz
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500      
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bstock
    username: bstockuser
    password: postgresql
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true   
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 200
        max-idle: 500
        min-idle: 10
        max-wait: 100000
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: rabbitmq
    virtual-host: /
    pool:
      channelCacheSize: 5        
logging:
  config: classpath:logback.xml
  
springdoc:
  api-docs:
    path: /biz/swagger/v3/api-docs  
  swagger-ui:
    path: /biz/swagger/swagger-ui.html  
    
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: http://localhost:14268/api/traces
    sampler:
      type: const
      param: 1
