server:
  port: 11081  
  oauth2:
    url: http://bigstock-gateway:10093  
    secret-key: 4903837210390382930293802938293802932038203920382039203820392038
spring:
  main: 
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: bigstock-gateway
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: /
    pool:
      channelCacheSize: 5    
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  sleuth:
    sampler:
      probability: 1.0      
  cloud:
    consul:
      host: ${SPRING_CONSUL_HOST}
      port: ${SPRING_CONSUL_PORT}    
    discovery:
      health-check-path: /actuator/health # 设置健康检查路径为 Actuator 的健康端点路径
      health-check-interval: 15s # 设置健康检查间隔为 15 秒
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # 设置实例ID
    gateway:
      routes:
      - id: big-stcok-biz-http-api
        uri: lb://bigstock-biz
        predicates:
          - Path=/api/biz/**
        filters:
          - StripPrefix=1
      - id: big-stock-auth
        uri: lb://bigstock-auth
        predicates:
        - Path=/auth/**

logging:
  config: classpath:logback.xml
  
management:
  endpoints:
    web:
      exposure:
        include: "*" # 包含所有的Actuator端点，可以根据需要进行调整
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true  
  
springdoc:
  api-docs:
    path: /gateway/swagger/v3/api-docs     
  swagger-ui:
    path: /gateway/swagger/swagger-ui.html  
    enable: true
    supportHeaderParams: true
    config-url: /gateway/swagger/v3/api-docs/swagger-config
    urls:
      - url: /gateway/swagger/v3/api-docs   
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /auth/swagger/v3/api-docs 
        name: Auth Service
        primaryName: Auth Service
      - url: /api/biz/swagger/v3/api-docs
        name: Biz Service
        primaryName: Biz Service
opentracing:
  jaeger:
    enabled: true
    http-sender:
      url: ${OPENTRACING_JAEGER_HTTP-SENDER}
      #http://localhost:14268/api/traces
    sampler:
      type: const
      param: ${OPENTRACING_JAEGER_SAMPLER_PARAM}
    reporter:
      log-spans: true
      flush-interval: 1000
      max-queue-size: 10000       
